<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_jam_kerja_model extends CI_Model
{

    public $table = 'tbl_jam_kerja';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    
    function json($role){
        $disabled='disabled';
        if ($role == 1) {
            $disabled='';
        }
        $this->datatables->select('tbl_jam_kerja.id, business_locations.name, jam_datang, jam_pulang');
        $this->datatables->from('tbl_jam_kerja');
        $this->datatables->join('business_locations', 'business_locations.id=tbl_jam_kerja.location_id');
        $this->datatables->add_column('action', anchor(site_url('hrms/jamkerja/update/$1'),'<i class="fa fa-edit" aria-hidden="true"></i>','class="btn btn-success btn-sm '.$disabled.'"')." 
                ".anchor(site_url('hrms/jamkerja/delete/$1'),'<i class="fa fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm '.$disabled.'" onclick="javasciprt: return confirm(\'Are You Sure ?\')"', $disabled), 'id');
            
        return $this->datatables->generate();
    }

}

/* End of file Tbl_pasien_model.php */
/* Location: ./application/models/Tbl_pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-03 15:02:10 */
/* http://harviacode.com */