<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('users.id, users.username, users.email, tbl_pegawai.nama_pegawai');
        $this->datatables->from('users');
        $this->datatables->join('tbl_pegawai', 'tbl_pegawai.id_pegawai=users.id_pegawai', 'left');
        $this->datatables->add_column('action', anchor(site_url('user/update/$1'),'<i class="fa fa-edit" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm', 'title' => 'Edit Pegawai'))." 
                ".anchor(site_url('user/delete/$1'),'<i class="fa fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm" title = "Hapus Pegawai" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all($location_id)
    {
        $this->db->order_by($this->id, $this->order);
        if ($location_id != null) {
            $this->datatables->where('location_id', $location_id);
        }
        return $this->db->get($this->table)->result();
    }
    
    function get_all_jaga($id_klinik = null)
    {
        // $this->db->order_by($this->id, $this->order);
        $this->db->from('tbl_dokter');
        $this->db->join('tbl_user','tbl_dokter.id_dokter=tbl_user.id_dokter', 'left');
        $this->db->where('is_jaga', 1);
        if($id_klinik != null)
            $this->db->where('tbl_user.id_klinik', $id_klinik);
            
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_dokter_model.php */
/* Location: ./application/models/Tbl_dokter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-27 18:45:56 */
/* http://harviacode.com */